// front/components/Sidebar.vue
<template>
  <div class="sidebar">
    <div class="sidebar-avatar">
      <img src="~/static/images/avatar.jpg" alt="" class="avatar" />
    </div>
    <div class="credentials">
      <h3><n-link to="/">Goncharov Nikita</n-link></h3>
    </div>
    <div class="menu">
      <ul class="menu-list">
        <li v-for="item of menuItems">
          <nuxt-link
            v-bind:to="item.src"
            v-bind:class="{ active: item.active }"
            >{{ item.title }}</nuxt-link
          >
        </li>
      </ul>
    </div>
    <div class="sidebar-footer">
      <div class="icons-container">
        <a href="https://github.com/goncharovnikita"
          ><img class="icon-img" src="~/assets/icons/github.svg" alt=""
        /></a>
        <a href="https://medium.com/@cashalot"
          ><img class="icon-img" src="~/assets/icons/medium.svg" alt=""
        /></a>
        <a href="https://twitter.com/jamberspof"
          ><img class="icon-img" src="~/assets/icons/twitter.svg" alt=""
        /></a>
      </div>
    </div></div
></template>

<script>
export default {
  props: {
    active: {
      type: String,
      required: true
    }
  },
  computed: {
    menuItems({ isMobile }) {
      return [
        {
          id: 'projects',
          title: 'Проекты',
          src: '/',
          active: false,
          desktopOnly: true
        },
        {
          id: 'weather',
          title: 'Погода',
          src: '/weather',
          active: false,
          desktopOnly: true
        }
      ]
        .filter(({ desktopOnly }) => {
          if (desktopOnly) {
            return !isMobile
          }

          return true
        })
        .map((item) => {
          return {
            ...item,
            active: item.id === this.active
          }
        })
    }
  }
}
</script>

<style lang="scss" scoped>
.sidebar {
  height: 100%;
  grid-area: sidebar;
  background-color: var(--sidebar-color);
  display: grid;
  grid-template-rows: auto auto 1fr auto;
  grid-template-areas: 'avatar' 'credentials' 'info' 'side-footer';
  overflow-y: hidden;
  opacity: 0.8;
}
.sidebar-avatar {
  height: 100%;
  grid-area: avatar;
  min-width: 0;
  display: grid;
  grid-template-columns: 25% 50% 25%;
  grid-template-areas: '. avatar-photo .';
  padding: 41px 12px;
}
.menu {
  grid-area: info;
  padding: 36px;

  &-list {
    list-style-type: none;
    font-size: 20px;
    li {
      margin-bottom: 12px;
      a {
        text-decoration: none;
        color: #000000;
        &.active {
          font-weight: bold;
          border-bottom: 2px solid #000000;
        }
      }
    }
  }
}
.avatar {
  height: 140px;
  grid-area: avatar-photo;
  width: initial;
  align-self: center;
  border-radius: 25px;
  justify-self: center;
}
.credentials {
  grid-area: credentials;
  align-self: center;
  justify-self: center;
  background-color: var(--primary-color);
  width: 100%;
  padding: 19px 0;

  h3 {
    font-weight: bold;
    color: var(--accent-color);
    margin: 0;
    text-align: center;
    font-weight: 500;
    font-size: 24px;
    a {
      text-decoration: none;
      color: var(--accent-color);
    }
  }
}
.sidebar-footer {
  padding-bottom: 41px;
  grid-area: side-footer;
  width: 100%;
  justify-self: center;

  @media (max-width: 600px) {
    padding-bottom: 21px;
  }
}
.icons-container {
  display: flex;
  justify-content: center;
}
.icon-img {
  height: 36px;
  width: auto;
  margin: 0 29px;
}
</style>

// front/components/Sidebar/index.jsx
import Link from "next/link";
import cls from "classnames";

import styles from "./index.module.scss";

const links = [
    {
        id: "projects",
        title: "Проекты",
        href: "/",
        desktopOnly: true
    },
    {
        id: "weather",
        title: "Погода",
        href: "/weather",
        desktopOnly: true
    }
];

function Sidebar(props) {
    return (
        <div className={styles.container}>
            <div className={styles.avatar}>
                <img
                    src={require("images/avatar.jpg?webp&resize&size=280")}
                    load="lazy"
                    alt=""
                    className={styles.avatarImg}
                />
            </div>
            <div className={styles.credentials}>
                <h3 className="font-title">
                    <Link href="/">
                        <a>Goncharov Nikita</a>
                    </Link>
                </h3>
            </div>
            <div className={styles.menu}>
                <ul className={styles.menuList}>
                    {links.map(item => (
                        <li
                            key={item.id}
                            className={cls({
                                [styles.active]: props.active === item.id
                            })}
                        >
                            <Link href={item.href}>
                                <a>
                                    <span>{item.title}</span>
                                </a>
                            </Link>
                        </li>
                    ))}
                </ul>
            </div>
            <div className={styles.footer}>
                <div className={styles.iconsContainer}>
                    <a href="https://github.com/goncharovnikita" className={styles.link}>
                        <img
                            className={styles.iconImg}
                            src="/icons/github.svg"
                            alt=""
                        />
                    </a>
                    <a href="https://medium.com/@cashalot" className={styles.link}>
                        <img
                            className={styles.iconImg}
                            src="/icons/medium.svg"
                            alt=""
                        />
                    </a>
                    <a href="https://twitter.com/jamberspof" className={styles.link}>
                        <img
                            className={styles.iconImg}
                            src="/icons/twitter.svg"
                            alt=""
                        />
                    </a>
                </div>
            </div>
        </div>
    );
}

export default Sidebar;
