// front2/components/ContentTitle.jsx
import styled from 'styled-components';

const Container = styled.div`
  padding: 20px 41px;
`;

const Title = styled.h2`
  color: white;
  margin-bottom: 14px;
`;

const Divider = styled.hr`
  height: 3px;
  background-color: #000000;
  border: none;
`;

export default function ContentTitle(props) {
  return (
    <Container>
      <Title>{props.children}</Title>
      <Divider />
    </Container>
  );
}

// front/components/ContentTitle.vue
<template
  ><div class="container">
    <h2 class="title">
      <slot />
    </h2>
    <hr class="divider" /></div
></template>

<style lang="scss" scoped>
.container {
  padding: 20px 41px;
}
.title {
  color: white;
  margin-bottom: 14px;
}
.divider {
  height: 3px;
  background-color: #000000;
  border: none;
}
</style>
