// front2/components/ProjectCard.jsx
import styled from 'styled-components';

import ProjectLink from './ProjectLink';

export default function ProjectCard(props) {
  const {href, img, title, description, links} = props;

  return (
    <Container>
      <Title>
        <p className="title">
          <a href={href} rel="noopener noreferrer" target="_blank">
            {title}
          </a>
        </p>
      </Title>
      <ImgContainer>
        <img src={img} alt={title} className="img" />
      </ImgContainer>
      <DescriptionContainer>
        <p className="description-text">{description}</p>
        <Divider />
        <div className="links">
          {links.map(link => (
            <ProjectLink key={link.href} type={link.type} href={link.href} />
          ))}
        </div>
      </DescriptionContainer>
    </Container>
  );
}

const Container = styled.div`
  display: grid;
  grid-template: 'title title' 'image description';
  grid-template-rows: auto 1fr;
  grid-template-columns: auto 1fr;
  grid-row-gap: 24px;
  grid-column-gap: 24px;
  background-color: var(--sidebar-color);
  padding: 24px 32px;
`;

const Title = styled.div`
  grid-area: title;
  .title {
    font-size: 24px;
    font-weight: 900;
  }
`;

const ImgContainer = styled.div`
  grid-area: image;
  .img {
    height: 120px;
    width: 120px;
  }
`;

const DescriptionContainer = styled.div`
  grid-area: description;
`;

const Divider = styled.hr`
  margin-top: 24px;
  margin-bottom: 8px;
`;

// front/components/ProjectCard.vue
<template>
  <div class="container">
    <div class="title-container">
      <p class="title">
        <a v-bind:href="href" rel="noopener noreferrer" target="_blank">{{
          title
        }}</a>
      </p>
    </div>
    <div class="img-container">
      <img v-bind:src="img" v-bind:alt="title" class="img" />
    </div>
    <div class="description-container">
      <p class="description-text">
        {{ description }}
      </p>
      <hr class="divider" />
      <div class="links">
        <project-link
          v-for="link of links"
          v-bind:type="link.type"
          v-bind:src="link.src"
        />
      </div>
    </div>
  </div>
</template>

<script>
import ProjectLink from '~/components/ProjectLink'

export default {
  components: {
    ProjectLink
  },
  props: {
    title: {
      type: String,
      required: true
    },
    description: {
      type: String,
      required: true
    },
    href: {
      type: String,
      required: true
    },
    img: {
      type: String,
      required: true
    },
    links: {
      type: Array,
      required: false,
      default() {
        return []
      }
    }
  }
}
</script>

<style lang="scss" scoped>
.container {
  display: grid;
  grid-template: 'title title' 'image description';
  grid-template-rows: auto 1fr;
  grid-template-columns: auto 1fr;
  grid-row-gap: 24px;
  grid-column-gap: 24px;
  background-color: var(--sidebar-color);
  padding: 24px 32px;
}

.title-container {
  grid-area: title;
  .title {
    font-size: 24px;
    font-weight: 900;
  }
}

.img-container {
  grid-area: image;
  .img {
    height: 120px;
    width: 120px;
  }
}

.description-container {
  grid-area: description;
}
.divider {
  margin-top: 24px;
  margin-bottom: 8px;
}
</style>
